### ISSUE TITLE
just out of curiosity

### ISSUE THREAD

**Issue by S1SYPHOS** [jenstornell/kirby-starthook#2]
.. all your code are belong to tab spaces ..

![](http://i0.kym-cdn.com/photos/images/original/000/976/824/913.gif)

**Comment by jenstornell** [comment]
Why not? :O)

**Comment by S1SYPHOS** [comment]
I already thought about sending some PRs, but you (intentionally) did it all over the place, I just HAD to ask :poodle:

**Comment by jenstornell** [comment]
I use Visual Studio Code nowdays, so I think all newer code will use spaces.

**Comment by S1SYPHOS** [comment]
So, if I happen to send PRs just for the sake of (too much spare time obviously, but also) indentation, that's okay?
